import { useState } from "react";
import { Download, FileText, FileCode, Loader2, ChevronDown } from "lucide-react";
import { toast } from "react-hot-toast";
import { API_BASE } from "../../config/api";

interface ExportDocButtonProps {
  content: string;
  titlePrefix?: string;
}

function extractDocumentTitle(text: string, fallback?: string): string {
  if (fallback && fallback !== "Sastra_AI_Response") return fallback;
  // Match markdown H1 # Title or H2 ## Title
  const headingMatch = text.match(/^#+\s*([^\n]+)/m);
  if (headingMatch && headingMatch[1].trim()) {
    return headingMatch[1].replace(/[*_`#]/g, "").trim().slice(0, 70);
  }
  // Match bold title **Title**
  const boldMatch = text.match(/^\s*\*\*([^\*\n]+)\*\*/m);
  if (boldMatch && boldMatch[1].trim()) {
    return boldMatch[1].trim().slice(0, 70);
  }
  // First clean line
  const lines = text.trim().split("\n");
  for (const line of lines) {
    const clean = line.replace(/[*_`#\-]/g, "").trim();
    if (clean.length > 3 && clean.length <= 70 && !clean.startsWith("http")) {
      return clean;
    }
  }
  return "Sastra AI Document";
}

export function ExportDocButton({ content, titlePrefix }: ExportDocButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState<string | null>(null);

  const handleExport = async (format: "pdf" | "docx" | "md" | "csv") => {
    setIsExporting(format);
    setIsOpen(false);
    try {
      const title = extractDocumentTitle(content, titlePrefix);
      const res = await fetch(`${API_BASE}/api/documents/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title,
          format,
          content,
          subtitle: "Generated by Sastra AI Assistant",
        }),
      });

      if (!res.ok) {
        throw new Error("Failed to generate document");
      }

      const data = await res.json();
      // Trigger download
      const link = document.createElement("a");
      link.href = `${API_BASE}${data.download_url}`;
      link.setAttribute("download", data.filename);
      link.setAttribute("target", "_blank");
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      toast.success(`${format.toUpperCase()} document downloaded!`);
    } catch (err: any) {
      toast.error(err.message || "Export failed");
    } finally {
      setIsExporting(null);
    }
  };

  return (
    <div className="relative inline-block text-left">
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        disabled={!!isExporting}
        className="flex items-center gap-1 rounded-md px-1.5 py-1 text-xs text-stone-400 hover:text-gold hover:bg-gold/10 transition-colors"
        title="Export reply as document"
      >
        {isExporting ? (
          <Loader2 className="h-3.5 w-3.5 animate-spin text-gold" />
        ) : (
          <Download className="h-3.5 w-3.5" />
        )}
        <span className="hidden sm:inline text-[11px] font-medium">Export</span>
        <ChevronDown className="h-3 w-3" />
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 bottom-full mb-1 z-50 w-36 rounded-xl border border-[#3C301D] bg-[#14100B] p-1 shadow-xl animate-fade-in">
            <button
              onClick={() => handleExport("pdf")}
              className="flex w-full items-center gap-2 rounded-lg px-2.5 py-1.5 text-left text-xs text-stone-200 hover:bg-gold/15 hover:text-gold transition-colors"
            >
              <FileText className="h-3.5 w-3.5 text-rose-400" />
              <span>Export PDF</span>
            </button>
            <button
              onClick={() => handleExport("docx")}
              className="flex w-full items-center gap-2 rounded-lg px-2.5 py-1.5 text-left text-xs text-stone-200 hover:bg-gold/15 hover:text-gold transition-colors"
            >
              <FileText className="h-3.5 w-3.5 text-sky-400" />
              <span>Export Word (.docx)</span>
            </button>
            <button
              onClick={() => handleExport("md")}
              className="flex w-full items-center gap-2 rounded-lg px-2.5 py-1.5 text-left text-xs text-stone-200 hover:bg-gold/15 hover:text-gold transition-colors"
            >
              <FileCode className="h-3.5 w-3.5 text-amber-400" />
              <span>Export Markdown</span>
            </button>
          </div>
        </>
      )}
    </div>
  );
}
